import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';
import 'dart:async';
import 'dart:ui';
import 'package:screen_brightness/screen_brightness.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart' hide Video;
import 'package:shared_preferences/shared_preferences.dart';

// 🌟 引入你的 API 和工具类以支持网络请求和弹窗
import '../services/api_service.dart';
import '../core/utils.dart';

class PlayerScreen extends StatefulWidget {
  final String streamUrl;
  final String title;

  const PlayerScreen({super.key, required this.streamUrl, required this.title});

  @override
  State<PlayerScreen> createState() => _PlayerScreenState();
}

class _PlayerScreenState extends State<PlayerScreen> {
  late final player = Player(
    configuration: const PlayerConfiguration(
      // 🌟 增强网络流的缓冲能力，防止服务器推流时卡顿
      bufferSize: 1024 * 1024 * 64, // 64MB 缓冲区
    ),
  );
  late final controller = VideoController(player);

  final yt = YoutubeExplode();

  // 状态变量
  bool _hasError = false;
  String _errorMsg = '';
  bool _isPreparing = true;
  bool _isTranslating = false; // 🌟 新增：控制 AI 翻译按钮的转圈状态

  // UI 状态
  bool _showControls = true;
  bool _isLocked = false;
  Timer? _hideTimer;
  BoxFit _videoFit = BoxFit.contain;
  bool _isDraggingProgress = false;
  double _dragProgressValue = 0.0;

  // 手势状态
  double _volume = 50.0;
  double _brightness = 0.5;
  String _osdType = '';
  bool _showOsd = false;
  Timer? _osdHideTimer;
  double _startDragValue = 0.0;
  bool _isLeftSideDrag = true;
  int _lastHapticLevel = 0;

  @override
  void initState() {
    super.initState();
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,
    ]);
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersiveSticky);

    player.stream.error.listen((error) {
      debugPrint("🚨 播放器底层报错: $error");
      if (mounted) {
        setState(() {
          _hasError = true;
          _errorMsg = error.toString();
          _isPreparing = false;
        });
      }
    });

    _initBrightness();
    _initializeUniversalPlayer();
  }

  // 🌟🌟 核心魔法逻辑：前端硬解 YouTube / 播放服务器推流
  Future<void> _initializeUniversalPlayer() async {
    final isYouTube = widget.streamUrl.contains('youtube.com') || widget.streamUrl.contains('youtu.be');

    if (isYouTube) {
      try {
        debugPrint("🚀 开始前端直解 YouTube 链接: ${widget.streamUrl}");
        var videoId = VideoId(widget.streamUrl);

        var manifest = await yt.videos.streamsClient.getManifest(videoId);
        var streamInfo = manifest.muxed.withHighestBitrate();

        String? subtitleUrl;
        try {
          var trackManifest = await yt.videos.closedCaptions.getManifest(videoId);
          var tracks = trackManifest.getByLanguage('zh', autoGenerated: true);
          if (tracks.isNotEmpty) {
            subtitleUrl = tracks.first.url.toString();
          }
        } catch (e) {
          debugPrint("⚠️ 获取字幕失败，将无字幕播放: $e");
        }

        await player.open(Media(
          streamInfo.url.toString(),
          httpHeaders: {
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'
          },
        ));

        if (subtitleUrl != null) {
          player.setSubtitleTrack(SubtitleTrack.uri(subtitleUrl, title: 'AI 同传中字', language: 'zh'));
        }

      } catch (e) {
        if (mounted) {
          setState(() {
            _hasError = true;
            _errorMsg = "YouTube 解析被拦截，请重试或检查网络: $e";
            _isPreparing = false;
          });
        }
        return;
      }
    } else {
      // 🌟🌟 播放服务器离线视频
      debugPrint("🎬 开始播放服务器推流媒体: ${widget.streamUrl}");
      try {
        await player.open(Media(widget.streamUrl));
      } catch (e) {
        if (mounted) {
          setState(() {
            _hasError = true;
            _errorMsg = "服务器推流加载失败: $e";
            _isPreparing = false;
          });
        }
        return;
      }
    }

    player.setVolume(_volume);
    if (mounted) {
      setState(() => _isPreparing = false);
      _startHideTimer();
    }
  }

  Future<void> _initBrightness() async {
    try {
      _brightness = await ScreenBrightness().current;
    } catch (e) {
      debugPrint("获取亮度失败: $e");
    }
  }

  void _startHideTimer() {
    _hideTimer?.cancel();
    _hideTimer = Timer(const Duration(seconds: 4), () {
      if (mounted && !_isDraggingProgress) {
        setState(() => _showControls = false);
      }
    });
  }

  void _handleScreenTap() {
    if (_isLocked) {
      setState(() => _showControls = true);
      _startHideTimer();
      return;
    }
    setState(() => _showControls = !_showControls);
    if (_showControls) _startHideTimer();
  }

  void _showOsdIndicator(String type) {
    setState(() {
      _osdType = type;
      _showOsd = true;
    });
    _osdHideTimer?.cancel();
    _osdHideTimer = Timer(const Duration(seconds: 1), () {
      if (mounted) setState(() => _showOsd = false);
    });
  }

  // ==========================================
  // 🌟🌟 核心：触发 DeepSeek AI 翻译逻辑
  // ==========================================
  Future<void> _triggerDeepSeekTranslation() async {
    final isYouTube = widget.streamUrl.contains('youtube.com') || widget.streamUrl.contains('youtu.be');

    if (isYouTube) {
      Utils.showToast("YouTube 视频已默认挂载官方 AI 中文字幕！");
      return;
    }

    setState(() => _isTranslating = true);
    Utils.showToast("正在唤醒服务器 DeepSeek 引擎...");

    // 呼叫后端提取视频音频并进行翻译
    bool success = await ApiService.requestTranslation(widget.title);

    if (mounted) {
      setState(() => _isTranslating = false);
    }

    if (success) {
      Utils.showToast("翻译完成！正在挂载中文字幕...");

      // 假设服务器把翻译好的字幕托管在这个接口下
      try {
        final prefs = await SharedPreferences.getInstance();
        final apiUrl = prefs.getString('orbix_api_url') ?? 'https://api.dmitt.com';
        final baseUrl = apiUrl.replaceAll(RegExp(r'/api/sync$'), '');

        // 拼接获取字幕的流媒体地址
        final srtUrl = "$baseUrl/api/subtitle?torrent_name=${Uri.encodeComponent(widget.title)}";

        // 强制播放器加载刚才生成的纯中文字幕
        player.setSubtitleTrack(SubtitleTrack.uri(srtUrl, title: 'DeepSeek AI 中文', language: 'zh'));
      } catch (e) {
        debugPrint("挂载字幕失败: $e");
      }
    } else {
      Utils.showToast("请求失败：服务器正忙或翻译接口异常");
    }
  }

  @override
  void dispose() {
    _hideTimer?.cancel();
    _osdHideTimer?.cancel();
    SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
    ScreenBrightness().resetScreenBrightness();
    player.dispose();
    yt.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      backgroundColor: Colors.black,
      child: Stack(
        children: [
          Center(
            child: Video(
              controller: controller,
              fit: _videoFit,
              fill: Colors.transparent,
              subtitleViewConfiguration: const SubtitleViewConfiguration(
                style: TextStyle(
                  fontSize: 24,
                  color: Colors.white,
                  fontWeight: FontWeight.bold,
                  shadows: [Shadow(offset: Offset(1, 1), blurRadius: 4, color: Colors.black)],
                ),
              ),
            ),
          ),

          if (_isPreparing && !_hasError)
            Container(
              color: Colors.black.withOpacity(0.8),
              child: const Center(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    CupertinoActivityIndicator(radius: 20, color: Colors.white),
                    SizedBox(height: 16),
                    Text("智能嗅探多媒体源...", style: TextStyle(color: Colors.white70, fontSize: 14)),
                  ],
                ),
              ),
            ),

          if (!_isPreparing)
            GestureDetector(
              behavior: HitTestBehavior.translucent,
              onTap: _handleScreenTap,
              onDoubleTapDown: (details) {
                if (_isLocked) return;
                HapticFeedback.lightImpact();
                final screenWidth = MediaQuery.of(context).size.width;
                if (details.globalPosition.dx < screenWidth / 2) {
                  player.seek(player.state.position - const Duration(seconds: 10));
                } else {
                  player.seek(player.state.position + const Duration(seconds: 10));
                }
                _showOsdIndicator('seek');
              },
              onVerticalDragStart: (details) {
                if (_isLocked) return;
                final screenWidth = MediaQuery.of(context).size.width;
                _isLeftSideDrag = details.globalPosition.dx < screenWidth / 2;
                _startDragValue = _isLeftSideDrag ? _brightness : (_volume / 100.0);
                _lastHapticLevel = (_startDragValue * 20).toInt();
              },
              onVerticalDragUpdate: (details) {
                if (_isLocked) return;
                final screenHeight = MediaQuery.of(context).size.height;
                final delta = -details.primaryDelta! / (screenHeight * 0.8);

                double newValue = (_startDragValue + delta).clamp(0.0, 1.0);
                _startDragValue = newValue;

                int currentLevel = (newValue * 20).toInt();
                if (currentLevel != _lastHapticLevel) {
                  HapticFeedback.selectionClick();
                  _lastHapticLevel = currentLevel;
                }

                setState(() {
                  if (_isLeftSideDrag) {
                    _brightness = newValue;
                    ScreenBrightness().setScreenBrightness(_brightness);
                    _showOsdIndicator('brightness');
                  } else {
                    _volume = newValue * 100;
                    player.setVolume(_volume);
                    _showOsdIndicator('volume');
                  }
                });
              },
            ),

          Center(
            child: AnimatedOpacity(
              opacity: _showOsd ? 1.0 : 0.0,
              duration: const Duration(milliseconds: 200),
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
                decoration: BoxDecoration(
                  color: Colors.black.withOpacity(0.65),
                  borderRadius: BorderRadius.circular(16),
                  boxShadow: const [BoxShadow(color: Colors.black26, blurRadius: 10, spreadRadius: 2)],
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(_getOsdIcon(), color: Colors.white, size: 28),
                    const SizedBox(width: 16),
                    SizedBox(
                      width: 120,
                      child: ClipRRect(
                        borderRadius: BorderRadius.circular(6),
                        child: LinearProgressIndicator(
                          value: _osdType == 'volume' ? _volume / 100.0 : _brightness,
                          backgroundColor: Colors.white24,
                          valueColor: const AlwaysStoppedAnimation(Colors.white),
                          minHeight: 6,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),

          if (!_isPreparing)
            AnimatedOpacity(
              opacity: _showControls ? 1.0 : 0.0,
              duration: const Duration(milliseconds: 300),
              child: IgnorePointer(
                ignoring: !_showControls,
                child: Stack(
                  children: [
                    if (!_isLocked) ...[
                      Positioned(top: 0, left: 0, right: 0, child: _buildTopBar()),
                      Center(child: _buildCenterPlayButton()),
                      Positioned(bottom: 0, left: 0, right: 0, child: _buildBottomBar()),
                    ],
                    Positioned(
                      left: 40,
                      top: 0,
                      bottom: 0,
                      child: Center(
                        child: CupertinoButton(
                          padding: EdgeInsets.zero,
                          onPressed: () {
                            HapticFeedback.mediumImpact();
                            setState(() {
                              _isLocked = !_isLocked;
                              if (!_isLocked) _startHideTimer();
                            });
                          },
                          child: Container(
                            decoration: BoxDecoration(
                              color: _isLocked ? Colors.redAccent.withOpacity(0.8) : Colors.black.withOpacity(0.5),
                              shape: BoxShape.circle,
                            ),
                            padding: const EdgeInsets.all(12),
                            child: Icon(
                              _isLocked ? CupertinoIcons.lock_fill : CupertinoIcons.lock_open_fill,
                              color: Colors.white,
                              size: 24,
                            ),
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
        ],
      ),
    );
  }

  IconData _getOsdIcon() {
    if (_osdType == 'volume') {
      if (_volume == 0) return CupertinoIcons.volume_mute;
      if (_volume < 50) return CupertinoIcons.volume_down;
      return CupertinoIcons.volume_up;
    } else if (_osdType == 'brightness') {
      return CupertinoIcons.brightness;
    }
    return CupertinoIcons.play_fill;
  }

  Widget _buildCenterPlayButton() {
    if (_hasError) {
      return Container(
        padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
        decoration: BoxDecoration(
          color: Colors.black.withOpacity(0.7),
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: Colors.redAccent.withOpacity(0.5)),
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(CupertinoIcons.exclamationmark_triangle_fill, color: Colors.redAccent, size: 36),
            const SizedBox(height: 12),
            const Text("流媒体加载失败", style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
            const SizedBox(height: 6),
            SizedBox(
              width: 250,
              child: Text(
                _errorMsg,
                textAlign: TextAlign.center,
                style: const TextStyle(color: Colors.white70, fontSize: 12),
                maxLines: 3,
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ],
        ),
      );
    }

    return StreamBuilder<bool>(
      stream: player.stream.buffering,
      initialData: player.state.buffering,
      builder: (context, snapshot) {
        final isBuffering = snapshot.data ?? true;

        return AnimatedSwitcher(
          duration: const Duration(milliseconds: 300),
          child: isBuffering
              ? ClipRRect(
                  key: const ValueKey('buffering'),
                  borderRadius: BorderRadius.circular(16),
                  child: BackdropFilter(
                    filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
                    child: Container(
                      decoration: BoxDecoration(
                        color: Colors.black.withOpacity(0.55),
                        borderRadius: BorderRadius.circular(16),
                        border: Border.all(color: Colors.white10, width: 1),
                      ),
                      padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 20),
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: const [
                          CupertinoActivityIndicator(radius: 16, color: Colors.white),
                          SizedBox(height: 14),
                          Text(
                            "正在缓冲...",
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 14,
                              fontWeight: FontWeight.w600,
                              letterSpacing: 1.5,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                )
              : CupertinoButton(
                  key: const ValueKey('play_btn'),
                  padding: EdgeInsets.zero,
                  onPressed: () {
                    HapticFeedback.lightImpact();
                    player.playOrPause();
                    _startHideTimer();
                  },
                  child: Container(
                    decoration: BoxDecoration(
                      color: Colors.black.withOpacity(0.4),
                      shape: BoxShape.circle,
                    ),
                    padding: const EdgeInsets.all(18),
                    child: StreamBuilder<bool>(
                      stream: player.stream.playing,
                      initialData: player.state.playing,
                      builder: (context, playing) => Icon(
                        playing.data == true ? CupertinoIcons.pause_fill : CupertinoIcons.play_fill,
                        color: Colors.white,
                        size: 52,
                      ),
                    ),
                  ),
                ),
        );
      },
    );
  }

  Widget _buildTopBar() {
    return ClipRect(
      child: BackdropFilter(
        filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
        child: Container(
          height: 80,
          padding: const EdgeInsets.symmetric(horizontal: 20),
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
              colors: [Colors.black.withOpacity(0.7), Colors.transparent],
            ),
          ),
          child: Row(
            children: [
              CupertinoButton(
                padding: EdgeInsets.zero,
                child: const Icon(CupertinoIcons.back, color: Colors.white, size: 28),
                onPressed: () => Navigator.pop(context),
              ),
              const SizedBox(width: 15),
              Expanded(
                child: Text(
                  widget.title,
                  style: const TextStyle(
                    color: Colors.white,
                    fontSize: 17,
                    fontWeight: FontWeight.w600,
                    letterSpacing: 0.5,
                  ),
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                ),
              ),
              // 🌟 新增：顶部的 AI 魔术棒翻译按钮
              CupertinoButton(
                padding: EdgeInsets.zero,
                onPressed: _isTranslating ? null : _triggerDeepSeekTranslation,
                child: _isTranslating
                    ? const CupertinoActivityIndicator(color: Colors.white)
                    : const Icon(CupertinoIcons.wand_stars, color: Colors.white, size: 28),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildBottomBar() {
    return ClipRect(
      child: BackdropFilter(
        filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
        child: Container(
          padding: const EdgeInsets.fromLTRB(30, 20, 30, 40),
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.bottomCenter,
              end: Alignment.topCenter,
              colors: [Colors.black.withOpacity(0.7), Colors.transparent],
            ),
          ),
          child: StreamBuilder(
            stream: player.stream.position,
            builder: (context, pos) {
              final realPosition = pos.data ?? Duration.zero;
              final duration = player.state.duration;

              final currentSliderValue = _isDraggingProgress ? _dragProgressValue : realPosition.inSeconds.toDouble();
              final maxSliderValue = duration.inSeconds.toDouble().clamp(0.01, double.infinity);

              return Row(
                children: [
                  Text(_formatDuration(Duration(seconds: currentSliderValue.toInt())),
                      style: const TextStyle(color: Colors.white, fontSize: 13, fontFamily: 'Courier')),
                  Expanded(
                    child: CupertinoSlider(
                      value: currentSliderValue.clamp(0.0, maxSliderValue),
                      max: maxSliderValue,
                      activeColor: Colors.white,
                      thumbColor: Colors.white,
                      onChangeStart: (v) {
                        setState(() {
                          _isDraggingProgress = true;
                          _dragProgressValue = v;
                        });
                        _hideTimer?.cancel();
                      },
                      onChanged: (v) => setState(() => _dragProgressValue = v),
                      onChangeEnd: (v) {
                        HapticFeedback.selectionClick();
                        player.seek(Duration(seconds: v.toInt()));
                        setState(() => _isDraggingProgress = false);
                        _startHideTimer();
                      },
                    ),
                  ),
                  Text(_formatDuration(duration),
                      style: const TextStyle(color: Colors.white70, fontSize: 13, fontFamily: 'Courier')),
                  const SizedBox(width: 20),
                  CupertinoButton(
                    padding: EdgeInsets.zero,
                    minSize: 30,
                    onPressed: () {
                      HapticFeedback.lightImpact();
                      setState(() {
                        if (_videoFit == BoxFit.contain) {
                          _videoFit = BoxFit.cover;
                        } else if (_videoFit == BoxFit.cover) {
                          _videoFit = BoxFit.fill;
                        } else {
                          _videoFit = BoxFit.contain;
                        }
                      });
                      _startHideTimer();
                    },
                    child: Icon(
                      _videoFit == BoxFit.contain
                          ? CupertinoIcons.rectangle_expand_vertical
                          : CupertinoIcons.rectangle_arrow_up_right_arrow_down_left,
                      color: Colors.white,
                      size: 22,
                    ),
                  ),
                ],
              );
            },
          ),
        ),
      ),
    );
  }

  String _formatDuration(Duration d) {
    String twoDigits(int n) => n.toString().padLeft(2, "0");
    String twoDigitMinutes = twoDigits(d.inMinutes.remainder(60));
    String twoDigitSeconds = twoDigits(d.inSeconds.remainder(60));
    if (d.inHours > 0) return "${twoDigits(d.inHours)}:$twoDigitMinutes:$twoDigitSeconds";
    return "$twoDigitMinutes:$twoDigitSeconds";
  }
}