import SwiftUI

enum OrbixStrings {

    // MARK: - Navigation titles
    static let navSettings = String(localized: "设置", comment: "Settings tab")
    static let navAddTorrent = String(localized: "添加种子", comment: "Add torrent")
    static let navExplore = String(localized: "探索", comment: "Explore tab")
    static let navSearch = String(localized: "搜索", comment: "Search tab")
    static let navEditServer = String(localized: "编辑服务器", comment: "Edit server")
    static let navAddServer = String(localized: "添加服务器", comment: "Add server")
    static let navDetails = String(localized: "详情", comment: "Details")
    static let navFilePriority = String(localized: "文件优先级", comment: "File priority")
    static let navTrackerManagement = String(localized: "Tracker 管理", comment: "Tracker management")
    static let navAdvancedControl = String(localized: "高级控制", comment: "Advanced control")
    static let navTransferStats = String(localized: "传输统计", comment: "Transfer stats tab")
    static let navGlobalControl = String(localized: "全局控制", comment: "Global control")
    static let navAddToRadarr = String(localized: "添加到 Radarr", comment: "Add to Radarr")
    static let navAddTask = String(localized: "添加任务", comment: "Add task")
    static let navEditService = String(localized: "编辑服务", comment: "Edit service")
    static let navAddService = String(localized: "添加服务", comment: "Add service")
    static let navServerManagement = String(localized: "服务器管理", comment: "Server management")

    // MARK: - Tab bar
    static let tabTorrents = String(localized: "种子", comment: "Torrents tab")
    static let tabTransfer = String(localized: "传输", comment: "Transfer tab")
    static let tabSearch = String(localized: "搜索", comment: "Search tab")
    static let tabSettings = String(localized: "设置", comment: "Settings tab")

    // MARK: - Section headers
    static let sectionServer = String(localized: "服务器", comment: "Server section")
    static let sectionSecurity = String(localized: "安全", comment: "Security section")
    static let sectionServices = String(localized: "服务", comment: "Services section")
    static let sectionUpdate = String(localized: "更新", comment: "Update section")
    static let sectionName = String(localized: "名称", comment: "Name")
    static let sectionAddress = String(localized: "地址", comment: "Address")
    static let sectionUser = String(localized: "用户", comment: "User")
    static let sectionVersion = String(localized: "当前版本", comment: "Current version")
    static let sectionServerInfo = String(localized: "服务器信息", comment: "Server info")
    static let sectionAuth = String(localized: "认证", comment: "Authentication")
    static let sectionTransfer = String(localized: "传输", comment: "Transfer")
    static let sectionInfo = String(localized: "信息", comment: "Info")
    static let sectionTime = String(localized: "时间", comment: "Time")
    static let sectionMode = String(localized: "模式", comment: "Mode")
    static let sectionGlobalSpeedLimit = String(localized: "全局速度限制", comment: "Global speed limit")
    static let sectionSpeedLimit = String(localized: "速度限制", comment: "Speed limit")
    static let sectionDownloadMode = String(localized: "下载模式", comment: "Download mode")
    static let sectionLocation = String(localized: "位置", comment: "Location")
    static let sectionRename = String(localized: "重命名", comment: "Rename")
    static let sectionTorrentInfo = String(localized: "种子信息", comment: "Torrent info")
    static let sectionDownloadSettings = String(localized: "下载设置", comment: "Download settings")
    static let sectionAddTracker = String(localized: "添加 Tracker", comment: "Add tracker")
    static let sectionCurrentTrackers = String(localized: "当前 Trackers", comment: "Current trackers")
    static let sectionQualityConfig = String(localized: "质量配置", comment: "Quality config")
    static let sectionStoragePath = String(localized: "存储路径", comment: "Storage path")
    static let sectionServiceType = String(localized: "服务类型", comment: "Service type")
    static let sectionHost = String(localized: "主机", comment: "Host")
    static let sectionAddMethod = String(localized: "添加方式", comment: "Add method")
    static let sectionTorrentFile = String(localized: "种子文件", comment: "Torrent file")
    static let sectionAdvancedOptions = String(localized: "高级选项", comment: "Advanced options")

    // MARK: - DetailRow labels
    static let labelDownloadSpeed = String(localized: "下载速度", comment: "Download speed")
    static let labelUploadSpeed = String(localized: "上传速度", comment: "Upload speed")
    static let labelDownloaded = String(localized: "已下载", comment: "Downloaded")
    static let labelUploaded = String(localized: "已上传", comment: "Uploaded")
    static let labelRatio = String(localized: "分享率", comment: "Ratio")
    static let labelETA = String(localized: "预计完成", comment: "ETA")
    static let labelSeeds = String(localized: "种子/吸血", comment: "Seeds/leechers")
    static let labelTotalSize = String(localized: "总大小", comment: "Total size")
    static let labelSavePath = String(localized: "保存路径", comment: "Save path")
    static let labelCategory = String(localized: "分类", comment: "Category")
    static let labelTags = String(localized: "标签", comment: "Tags")
    static let labelAddTime = String(localized: "添加时间", comment: "Add time")
    static let labelCompleteTime = String(localized: "完成时间", comment: "Complete time")
    static let labelDownloadLimit = String(localized: "下载限速", comment: "Download limit")
    static let labelUploadLimit = String(localized: "上传限速", comment: "Upload limit")
    static let labelDownloadCategory = String(localized: "下载分类", comment: "Download category")
    static let labelAltSpeedMode = String(localized: "备用限速模式", comment: "Alt speed mode")

    // MARK: - Stats labels
    static let statsCurrSpeed = String(localized: "当前总速度", comment: "Current total speed")
    static let statsVolume = String(localized: "传输量", comment: "Transfer volume")
    static let statsConnection = String(localized: "连接", comment: "Connection")
    static let statsDisk = String(localized: "磁盘", comment: "Disk")
    static let statsOverview = String(localized: "概览", comment: "Overview")
    static let statsSessionDL = String(localized: "会话下载", comment: "Session download")
    static let statsSessionUL = String(localized: "会话上传", comment: "Session upload")
    static let statsTotalDL = String(localized: "总计下载", comment: "Total download")
    static let statsTotalUL = String(localized: "总计上传", comment: "Total upload")
    static let statsGlobalRatio = String(localized: "全局分享率", comment: "Global ratio")
    static let statsWasted = String(localized: "浪费", comment: "Wasted")
    static let statsDHT = String(localized: "DHT 节点", comment: "DHT nodes")
    static let statsFreeSpace = String(localized: "可用空间", comment: "Free space")
    static let statsStatus = String(localized: "状态", comment: "Status")
    static let statsTotal = String(localized: "总计", comment: "Total")
    static let statsDownloading = String(localized: "下载中", comment: "Downloading")
    static let statsSeeding = String(localized: "做种中", comment: "Seeding")
    static let statsPaused = String(localized: "已暂停", comment: "Paused")
    static let statsChecking = String(localized: "检查中", comment: "Checking")
    static let statsError = String(localized: "错误", comment: "Error")

    // MARK: - Buttons
    static let btnSave = String(localized: "保存", comment: "Save")
    static let btnCancel = String(localized: "取消", comment: "Cancel")
    static let btnDone = String(localized: "完成", comment: "Done")
    static let btnClose = String(localized: "关闭", comment: "Close")
    static let btnAdd = String(localized: "添加", comment: "Add")
    static let btnEdit = String(localized: "编辑", comment: "Edit")
    static let btnDelete = String(localized: "删除", comment: "Delete")
    static let btnConnect = String(localized: "连接", comment: "Connect")
    static let btnManage = String(localized: "管理", comment: "Manage")
    static let btnRetry = String(localized: "重试", comment: "Retry")
    static let btnOK = String(localized: "确定", comment: "OK")
    static let btnSwitchServer = String(localized: "切换服务器", comment: "Switch server")
    static let btnCheckUpdate = String(localized: "检查更新", comment: "Check update")
    static let btnDownloadInstall = String(localized: "下载并安装", comment: "Download and install")
    static let btnTestConnection = String(localized: "测试连接", comment: "Test connection")
    static let btnStartSetup = String(localized: "开始配置", comment: "Start setup")
    static let btnManageServers = String(localized: "管理服务器", comment: "Manage servers")
    static let btnConfirmDownload = String(localized: "确定下载", comment: "Confirm download")
    static let btnAddAndSearch = String(localized: "添加并自动搜刮", comment: "Add and auto search")
    static let btnAddToQueue = String(localized: "添加到队列", comment: "Add to queue")
    static let btnCopyMagnet = String(localized: "复制磁力链接", comment: "Copy magnet link")
    static let btnDownloadTorrent = String(localized: "下载 .torrent 文件", comment: "Download .torrent file")
    static let btnApplyPath = String(localized: "应用路径", comment: "Apply path")
    static let btnApplyName = String(localized: "应用名称", comment: "Apply name")
    static let btnApplyLimit = String(localized: "应用限速", comment: "Apply speed limit")
    static let btnToggleSequential = String(localized: "切换顺序下载", comment: "Toggle sequential download")
    static let btnStart = String(localized: "启动", comment: "Start")
    static let btnPause = String(localized: "暂停", comment: "Pause")
    static let btnForce = String(localized: "强制", comment: "Force")
    static let btnRecheck = String(localized: "校验", comment: "Recheck")
    static let btnAnnounce = String(localized: "汇报", comment: "Announce")
    static let btnWait = String(localized: "请稍候", comment: "Please wait")
    static let btnDeleteTaskOnly = String(localized: "仅删除任务", comment: "Delete task only")
    static let btnDeleteTaskFiles = String(localized: "删除任务及文件", comment: "Delete task and files")
    static let btnIgnore = String(localized: "忽略", comment: "Ignore")
    static let btnNormal = String(localized: "正常", comment: "Normal")
    static let btnHigh = String(localized: "高", comment: "High")
    static let btnMax = String(localized: "最高", comment: "Maximum")

    // MARK: - Error / Status
    static let errLoadFailed = String(localized: "加载失败", comment: "Load failed")
    static let errCantLoadTorrent = String(localized: "无法加载种子信息", comment: "Cannot load torrent info")
    static let errBuiltInSearchFailed = String(localized: "内置搜索失败", comment: "Built-in search failed")
    static let errProwlarrFailed = String(localized: "Prowlarr 连接失败", comment: "Prowlarr connection failed")
    static let errRadarrFailed = String(localized: "Radarr 连接失败", comment: "Radarr connection failed")
    static let errNoResults = String(localized: "未找到相关资源", comment: "No results found")
    static let errNoSearchResults = String(localized: "未找到结果", comment: "No search results")
    static let errCheckFailed = String(localized: "检查失败", comment: "Check failed")
    static let msgConnTest = String(localized: "连接测试", comment: "Connection test")
    static let msgConnecting = String(localized: "连接中...", comment: "Connecting...")
    static let msgSearchingAll = String(localized: "正在全网检索...", comment: "Searching all sources...")
    static let msgFetchingLatest = String(localized: "正在获取最新资源...", comment: "Fetching latest...")
    static let msgAdding = String(localized: "添加中...", comment: "Adding...")
    static let msgDownloading = String(localized: "正在下载...", comment: "Downloading...")
    static let msgDownloadingDot = String(localized: "下载中...", comment: "Downloading...")
    static let msgReadyToUpload = String(localized: "准备上传", comment: "Ready to upload")
    static let msgClickSelectTorrent = String(localized: "点击选择 .torrent 文件", comment: "Click to select .torrent file")
    static let msgUpToDate = String(localized: "已是最新版本", comment: "Already up to date")
    static let msgAllLoaded = String(localized: "— 已加载全部 —", comment: "All loaded")
    static let msgBrowseHot = String(localized: "浏览热门", comment: "Browse hot")
    static let msgSearchSuggestion = String(localized: "搜索番号或名称", comment: "Search code or name")
    static let msgNoTorrents = String(localized: "暂无种子", comment: "No torrents")
    static let msgNoMatchingTorrents = String(localized: "没有匹配的种子", comment: "No matching torrents")
    static let msgNoBookmarked = String(localized: "没有收藏的种子", comment: "No bookmarked torrents")
    static let msgNoServer = String(localized: "暂无服务器", comment: "No servers")

    // MARK: - Placeholders
    static let phSearchKeyword = String(localized: "输入关键字或 Hash...", comment: "Enter keyword or hash")
    static let phServerName = String(localized: "例如：家庭 NAS", comment: "e.g. Home NAS")
    static let phHostAddress = String(localized: "IP 或域名", comment: "IP or domain")
    static let phPassword = String(localized: "输入密码", comment: "Enter password")
    static let phMagnet = String(localized: "输入 magnet 链接或 URL，每行一个", comment: "Enter magnet link or URL")
    static let phCategoryPlaceholder = String(localized: "分类", comment: "Category")
    static let phTagsPlaceholder = String(localized: "标签 (逗号分隔)", comment: "Tags (comma separated)")
    static let phSavePathPlaceholder = String(localized: "保存路径", comment: "Save path")
    static let phNewSavePath = String(localized: "输入新的保存路径", comment: "Enter new save path")
    static let phRename = String(localized: "重命名", comment: "Rename")
    static let phUnlimited = String(localized: "不限速", comment: "Unlimited")
    static let phTrackerURL = String(localized: "输入 Tracker URL ...", comment: "Enter tracker URL")
    static let phNoLimit = String(localized: "不限", comment: "Unlimited")
    static let phDefaultPath = String(localized: "默认路径", comment: "Default path")
    static let phOptional = String(localized: "可选", comment: "Optional")

    // MARK: - Help / Info text
    static let infoAppLockHint = String(localized: "应用进入后台超过 8 秒后将自动锁定", comment: "App lock hint")
    static let infoSSLHint = String(localized: "确保你的 qBittorrent 已配置 SSL 证书", comment: "SSL hint")
    static let infoTestHint = String(localized: "测试将尝试使用当前配置连接到 qBittorrent", comment: "Test connection hint")
    static let infoDeleteConfirm = String(localized: "确定要删除此种子吗？", comment: "Confirm delete torrent")
    static let infoEmptyZeroHint = String(localized: "留空或填 0 表示不限速", comment: "Empty or 0 means unlimited")
    static let infoSequentialHint = String(localized: "按文件顺序下载，适合预览媒体文件", comment: "Sequential download hint")
    static let infoProwlarrHint = String(localized: "请确认 Prowlarr 中已添加索引器", comment: "Prowlarr indexer hint")
    static let infoDefaultPathHint = String(localized: "留空则使用 qBittorrent 默认下载路径", comment: "Default path hint")
    static let infoAltSpeedHint = String(localized: "开启后使用备用限速方案", comment: "Alt speed hint")
    static let infoEmptyZeroGlobalHint = String(localized: "空或 0 表示不限制", comment: "Empty or 0 means no limit")
    static let infoRadarrHint = String(localized: "电影添加到库后将自动搜索并开始下载", comment: "Radarr add hint")
    static let infoAPIKeyHint = String(localized: "在 %@ 设置 → General 中找到 API Key", comment: "Find API key in service settings")
    static let infoConfigHint = String(localized: "配置 qBittorrent 连接", comment: "Configure qBittorrent connection")

    // MARK: - Welcome
    static let welcomeQBittorrent = String(localized: "qBittorrent 客户端", comment: "qBittorrent client")
    static let welcomeAddServer = String(localized: "建立连接", comment: "Establish connection")
    static let welcomeManageTorrents = String(localized: "管理种子", comment: "Manage torrents")

    // MARK: - Server
    static let serverSelect = String(localized: "选择服务器", comment: "Select server")
    static let serverNotAdded = String(localized: "还没有添加服务器", comment: "No servers added yet")

    // MARK: - Filters / Sorts
    static let filterAll = String(localized: "全部", comment: "All")
    static let sortDateAdded = String(localized: "添加时间", comment: "Date added")
    static let sortName = String(localized: "名称", comment: "Name")
    static let sortProgress = String(localized: "进度", comment: "Progress")
    static let sortSize = String(localized: "大小", comment: "Size")
    static let sortRatio = String(localized: "分享率", comment: "Ratio")
    static let sortDLSpeed = String(localized: "下载速度", comment: "Download speed")
    static let sortULSpeed = String(localized: "上传速度", comment: "Upload speed")

    // MARK: - Misc
    static let miscBiometric = String(localized: "生物识别", comment: "Biometric")
    static let miscNameOptional = String(localized: "名称（可选）", comment: "Name (optional)")
    static let miscHost = String(localized: "主机地址", comment: "Host address")
    static let miscPort = String(localized: "端口", comment: "Port")
    static let miscUsername = String(localized: "用户名", comment: "Username")
    static let miscPassword = String(localized: "密码", comment: "Password")
    static let miscEnableHTTPS = String(localized: "启用 HTTPS", comment: "Enable HTTPS")
    static let miscConnectSuccess = String(localized: "连接成功", comment: "Connection successful")
    static let miscQBVersion = String(localized: "qBittorrent 版本", comment: "qBittorrent version")
    static let miscFilm = String(localized: "消息", comment: "Message")
    static let miscCountResults = String(localized: "%d 个结果", comment: "N results")
    static let miscNoCategories = String(localized: "无可用分类", comment: "No categories available")
    static let miscNoCategory = String(localized: "无分类", comment: "No category")
    static let miscDeleteTorrentTitle = String(localized: "删除种子", comment: "Delete torrent title")
    static let miscSeedsPrefix = String(localized: "种子 ", comment: "Seeds prefix")
    static let miscInLibrary = String(localized: "已在库中", comment: "Already in library")
    static let miscBuiltInSearch = String(localized: "内置搜索", comment: "Built-in search")
    static let miscAddModeLink = String(localized: "链接", comment: "Link")
    static let miscAddModeFile = String(localized: "文件", comment: "File")
    static let miscOriginalJP = String(localized: "原文（日文）", comment: "Original (Japanese)")
    static let miscCode = String(localized: "番号", comment: "Code")
    static let miscPageLink = String(localized: "页面链接", comment: "Page link")
    static let miscBatch = String(localized: "批量", comment: "Batch")
    static let miscModifyPath = String(localized: "修改保存路径", comment: "Modify save path")
    static let miscBookmark = String(localized: "收藏", comment: "Bookmark")
    static let miscUnbookmark = String(localized: "取消收藏", comment: "Unbookmark")
    static let miscUpdateAvailable = String(localized: "更新可用", comment: "Update available")

    // MARK: - Batch / Edit mode
    static let btnSelectAll = String(localized: "全选", comment: "Select all")
    static let btnDeselectAll = String(localized: "取消全选", comment: "Deselect all")
    static let btnBatchPause = String(localized: "批量暂停", comment: "Batch pause")
    static let btnBatchResume = String(localized: "批量恢复", comment: "Batch resume")
    static let btnBatchDelete = String(localized: "批量删除", comment: "Batch delete")
    static let miscSelectedCount = String(localized: "已选 %d 项", comment: "Selected %d items")
    static let infoBatchDeleteConfirm = String(localized: "确定要删除选中的 %d 个种子吗？此操作不可撤销。", comment: "Confirm batch delete")

    // MARK: - Filter / Sort extras
    static let filterActive = String(localized: "活动中", comment: "Active")
    static let filterCompleted = String(localized: "已完成", comment: "Completed")

    // MARK: - Connection / Service
    static let sectionConnection = String(localized: "连接", comment: "Connection section")

    // MARK: - App Lock
    static let lockUnlockReason = String(localized: "解锁 Orbix", comment: "Unlock reason")
    static let lockFallbackTitle = String(localized: "输入密码", comment: "Enter password")
    static let lockLocked = String(localized: "已锁定", comment: "Locked")

    // MARK: - Credentials / Connection test
    static let connSuccess = String(localized: "连接成功", comment: "Connection successful")
    static let connInvalidHost = String(localized: "无法连接到服务器，请检查地址和端口", comment: "Cannot connect to server")
    static let connAuthFailed = String(localized: "认证失败，请检查 API Key 或用户名密码", comment: "Authentication failed")
    static let connTimeout = String(localized: "连接超时，请检查网络或防火墙", comment: "Connection timeout")
    static let connUnknown = String(localized: "无效响应", comment: "Invalid response")
    static let connServerReturn = String(localized: "服务器返回 %d：%@", comment: "Server returned %d: %@")
    static let connUnableConnect = String(localized: "无法连接 %@\n%@", comment: "Cannot connect %@: %@")

    // MARK: - Placeholders (extended)
    static let phPort = String(localized: "8080", comment: "Port placeholder")
    static let phUsername = String(localized: "admin", comment: "Username placeholder")
    static let phIP = String(localized: "192.168.1.100", comment: "IP address placeholder")

    // MARK: - Labels
    static let labelMagnetURL = String(localized: "Magnet / URL", comment: "Magnet/URL input label")
    static let labelHash = String(localized: "Hash", comment: "Hash label")
    static let labelAPIKey = String(localized: "API Key", comment: "API Key label")
    static let labelHTTPS = String(localized: "HTTPS", comment: "HTTPS label")
    static let labelTrackersCount = String(localized: "Trackers (%d)", comment: "Trackers count header")
    static let labelPeersCount = String(localized: "Peers (%d)", comment: "Peers count header")
    static let labelTMDBID = String(localized: "TMDB ID: %d", comment: "TMDB ID label")

    // MARK: - Welcome tiles
    static let welcomeSubtitle1 = String(localized: "配置你的 qBittorrent 服务器地址", comment: "Configure server address")
    static let welcomeSubtitle2 = String(localized: "快速连接到远程或本地服务器", comment: "Quick connect to server")
    static let welcomeSubtitle3 = String(localized: "轻松管理和监控所有种子任务", comment: "Manage torrent tasks")
}
